apiVersion: batch/v1
kind: Job
metadata:
  name: hello-intern-job 
spec:
  template:
    spec:
      containers:
      - name: hello-intern-job 
        image: rmccarth/hello-interns:f2f7a2d1252e444d2c166170a096742e1e21876f
      restartPolicy: Never
  backoffLimit: 4
